"""empty message

Revision ID: 49676ef65ddd
Revises: 522d17379af0
Create Date: 2023-02-23 10:44:40.814264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49676ef65ddd'
down_revision = '522d17379af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('character_birth_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('character_birth_year',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
