"""empty message

Revision ID: 522d17379af0
Revises: 97d99f472c13
Create Date: 2023-02-22 11:44:16.479409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522d17379af0'
down_revision = '97d99f472c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
