"""empty message

Revision ID: 66167bf40fb9
Revises: 7b1143e231b3
Create Date: 2023-02-18 11:39:48.047470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66167bf40fb9'
down_revision = '7b1143e231b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('surname', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
